import { useEffect, useState } from 'react';
import { MaterialIcons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { buildNegocioReceiptHtml } from '@/lib/negocioReceiptHtml';
import { formatCOP } from '@/lib/creditCalculator';
import { NegocioDatePicker } from '@/components/negocios/components/NegocioDatePicker';
import { fetchManagerBusinesses, fetchManagerPayments, type CollectionManager, type ManagerBusiness, type ManagerPayment } from '@/lib/cartera/carteraService';

export function CollectionManagerPaymentsModal({ visible, manager, colors, onClose, onOpenBusiness }: { visible:boolean; manager:CollectionManager|null; colors:any; onClose:()=>void; onOpenBusiness:(id:string)=>void }) {
  const managerId = manager?.id || '';
  const [scope,setScope]=useState<'performed'|'portfolio'>('performed'); const [businesses,setBusinesses]=useState<ManagerBusiness[]>([]); const [businessId,setBusinessId]=useState(''); const [businessOpen,setBusinessOpen]=useState(false);
  const [search,setSearch]=useState(''); const [status,setStatus]=useState<'todos'|'emitido'|'anulado'>('todos'); const [dateFrom,setDateFrom]=useState(''); const [dateTo,setDateTo]=useState(''); const [page,setPage]=useState(1); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false);
  useEffect(()=>{ if(!visible||!managerId)return; setData(null);setScope('performed');setBusinessId('');setSearch('');setStatus('todos');setDateFrom('');setDateTo('');setPage(1); fetchManagerBusinesses(managerId).then(setBusinesses).catch((e)=>Alert.alert('Error',e.message)); },[visible,managerId]);
  useEffect(()=>{ if(!visible||!managerId|| (dateFrom&&dateTo&&dateFrom>dateTo))return; setLoading(true); fetchManagerPayments(managerId,{scope,negocioId:businessId,dateFrom,dateTo,receiptStatus:status,search,page,pageSize:10}).then(setData).catch((e)=>Alert.alert('Error',e.message)).finally(()=>setLoading(false)); },[visible,managerId,scope,businessId,dateFrom,dateTo,status,search,page]);
  const options=scope==='portfolio'?businesses.filter((b)=>b.current_assignment):businesses;
  const shareReceipt=async(payment:ManagerPayment)=>{try{const html=buildNegocioReceiptHtml({receiptNumber:payment.virtual_receipt_number,status:payment.receipt_status,paidAt:payment.paid_at,amount:Number(payment.amount),physicalReceiptNumber:payment.receipt_number,negocioNumero:payment.negocio_numero,customerName:payment.customer_name,sellerName:payment.created_by_name,remainingBalance:Number(payment.remaining_balance)});const {uri}=await Print.printToFileAsync({html});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'application/pdf',dialogTitle:payment.virtual_receipt_number});}catch(e:any){Alert.alert('Error',e.message||'No fue posible compartir el recibo');}};
  const summary=data?.summary;
  return <Modal visible={visible} animationType="slide" presentationStyle="fullScreen" statusBarTranslucent={false} onRequestClose={onClose}><SafeAreaView edges={['top', 'bottom']} style={[styles.root,{backgroundColor:colors.background.default}]}><View style={[styles.header,{borderBottomColor:colors.divider}]}><View style={{ flex: 1, paddingRight: 12 }}><Text style={[styles.title,{color:colors.text.primary}]} numberOfLines={1}>Cobros de {manager?.full_name||'gestor'}</Text><Text style={{color:colors.text.secondary,fontSize:12}}>Historial y cartera asignada</Text></View><Pressable onPress={onClose} hitSlop={12} style={styles.closeButton}><MaterialIcons name="close" size={26} color={colors.text.primary}/></Pressable></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.segment}>{<Pressable onPress={()=>{setScope('performed');setBusinessId('');setPage(1)}} style={[styles.segmentButton,{backgroundColor:scope==='performed'?colors.primary.main:colors.background.paper,borderColor:colors.divider}]}><Text style={{color:scope==='performed'?colors.primary.contrastText:colors.text.primary,fontWeight:'700',fontSize:12}}>Registrados por él</Text></Pressable>}<Pressable onPress={()=>{setScope('portfolio');setBusinessId('');setPage(1)}} style={[styles.segmentButton,{backgroundColor:scope==='portfolio'?colors.primary.main:colors.background.paper,borderColor:colors.divider}]}><Text style={{color:scope==='portfolio'?colors.primary.contrastText:colors.text.primary,fontWeight:'700',fontSize:12}}>De negocios asignados</Text></Pressable></View>
    <Text style={{color:colors.text.secondary,fontSize:12}}>{scope==='performed'?`Pagos registrados personalmente por ${manager?.full_name||'el gestor'}.`:`Pagos de negocios asignados actualmente, aunque los haya registrado otro usuario.`}</Text>
    <View style={styles.metrics}><Metric label="Recaudo neto" value={formatCOP(Number(summary?.total_collected||0))} colors={colors}/><Metric label="Vigentes" value={String(summary?.valid_count||0)} colors={colors}/><Metric label="Anulados" value={String(summary?.voided_count||0)} colors={colors} error/><Metric label="Promedio" value={formatCOP(Number(summary?.average_payment||0))} colors={colors}/></View>
    <TextInput value={search} onChangeText={(v)=>{setSearch(v);setPage(1)}} placeholder="Buscar cliente, recibo o negocio" placeholderTextColor={colors.text.secondary} style={[styles.input,{borderColor:colors.divider,color:colors.text.primary,backgroundColor:colors.background.paper}]}/>
    <Pressable onPress={()=>setBusinessOpen(!businessOpen)} style={[styles.select,{borderColor:colors.divider,backgroundColor:colors.background.paper}]}><Text style={{color:colors.text.primary}}>{options.find(b=>b.negocio_id===businessId)?`#${options.find(b=>b.negocio_id===businessId)?.negocio_numero} · ${options.find(b=>b.negocio_id===businessId)?.customer_name}`:'Todos los negocios relacionados'}</Text><MaterialIcons name="expand-more" size={22} color={colors.text.secondary}/></Pressable>
    {businessOpen&&<View style={[styles.options,{borderColor:colors.divider,backgroundColor:colors.background.paper}]}><Pressable onPress={()=>{setBusinessId('');setBusinessOpen(false);setPage(1)}} style={styles.option}><Text style={{color:colors.text.primary}}>Todos los negocios</Text></Pressable>{options.slice(0,30).map(b=><Pressable key={b.negocio_id} onPress={()=>{setBusinessId(b.negocio_id);setBusinessOpen(false);setPage(1)}} style={styles.option}><Text style={{color:colors.text.primary}}>#{b.negocio_numero} · {b.customer_name}</Text><Text style={{color:colors.text.secondary,fontSize:11}}>{b.current_assignment?'Actual':'Histórico'}</Text></Pressable>)}</View>}
    <View style={styles.filters}><View style={styles.date}><NegocioDatePicker value={dateFrom} onChange={(v)=>{setDateFrom(v);setPage(1)}} colors={colors} label="Desde" accessibilityLabel="Fecha inicial" /></View><View style={styles.date}><NegocioDatePicker value={dateTo} onChange={(v)=>{setDateTo(v);setPage(1)}} colors={colors} label="Hasta" accessibilityLabel="Fecha final" /></View></View>
    <View style={styles.statuses}>{(['todos','emitido','anulado'] as const).map(s=><Pressable key={s} onPress={()=>{setStatus(s);setPage(1)}} style={[styles.status,{borderColor:colors.divider,backgroundColor:status===s?colors.primary.main:colors.background.paper}]}><Text style={{color:status===s?colors.primary.contrastText:colors.text.primary,fontWeight:'600'}}>{s==='todos'?'Todos':s==='emitido'?'Vigentes':'Anulados'}</Text></Pressable>)}</View>
    {dateFrom&&dateTo&&dateFrom>dateTo&&<Text style={{color:colors.error.main}}>La fecha inicial debe ser anterior a la final.</Text>}
    {loading?<ActivityIndicator color={colors.primary.main} style={{margin:25}}/>:data?.rows?.length?data.rows.map((p:ManagerPayment)=><View key={p.payment_id} style={[styles.payment,{backgroundColor:colors.background.paper,borderColor:colors.divider}]}><Pressable onPress={()=>onOpenBusiness(p.negocio_id)} style={{flex:1}}><Text style={{color:colors.text.primary,fontWeight:'700'}}>#{p.negocio_numero} · {p.customer_name}</Text><Text style={{color:colors.text.secondary,fontSize:12}}>{p.paid_at} · {p.installment_number?`Cuota ${p.installment_number}`:'Auto (FIFO)'}</Text><Text style={{color:colors.text.secondary,fontSize:12}}>{p.virtual_receipt_number} · {p.created_by_name}</Text></Pressable><View style={{alignItems:'flex-end',gap:5}}><Text style={{color:colors.text.primary,fontWeight:'700'}}>{formatCOP(Number(p.amount))}</Text><Text style={{color:p.receipt_status==='anulado'?colors.error.main:colors.success.main,fontSize:12,fontWeight:'700'}}>{p.receipt_status==='anulado'?'Anulado':'Vigente'}</Text><Pressable onPress={()=>shareReceipt(p)}><MaterialIcons name="picture-as-pdf" size={22} color={colors.primary.main}/></Pressable></View></View>):<Text style={[styles.empty,{color:colors.text.secondary}]}>No hay cobros para estos filtros.</Text>}
    <View style={styles.pager}><Pressable disabled={page===1} onPress={()=>setPage(p=>p-1)}><Text style={{color:page===1?colors.text.secondary:colors.primary.main,fontWeight:'700'}}>Anterior</Text></Pressable><Text style={{color:colors.text.secondary}}>Página {page} · {summary?.total_count||0} registros</Text><Pressable disabled={!data||page*10>=Number(summary?.total_count||0)} onPress={()=>setPage(p=>p+1)}><Text style={{color:!data||page*10>=Number(summary?.total_count||0)?colors.text.secondary:colors.primary.main,fontWeight:'700'}}>Siguiente</Text></Pressable></View>
  </ScrollView></SafeAreaView></Modal>;
}
function Metric({label,value,colors,error}:{label:string;value:string;colors:any;error?:boolean}){return <View style={[styles.metric,{backgroundColor:colors.background.paper,borderColor:colors.divider}]}><Text style={{color:colors.text.secondary,fontSize:10}}>{label}</Text><Text style={{color:error?colors.error.main:colors.text.primary,fontWeight:'700'}} numberOfLines={1}>{value}</Text></View>}
const styles=StyleSheet.create({root:{flex:1},header:{minHeight:64,paddingHorizontal:16,paddingVertical:12,flexDirection:'row',alignItems:'center',borderBottomWidth:1},closeButton:{width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:21},title:{fontSize:18,fontWeight:'700'},content:{padding:14,gap:10},segment:{flexDirection:'row',gap:6},segmentButton:{flex:1,padding:10,alignItems:'center',borderWidth:1,borderRadius:8},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{width:'48%',borderWidth:1,borderRadius:8,padding:9},input:{borderWidth:1,borderRadius:9,padding:11},select:{borderWidth:1,borderRadius:9,padding:11,flexDirection:'row',justifyContent:'space-between'},options:{borderWidth:1,borderRadius:9,maxHeight:220},option:{padding:11,borderBottomWidth:1},filters:{flexDirection:'row',gap:8},date:{flex:1},statuses:{flexDirection:'row',gap:7},status:{paddingVertical:8,paddingHorizontal:10,borderWidth:1,borderRadius:16},payment:{padding:12,borderWidth:1,borderRadius:10,flexDirection:'row',gap:8},empty:{textAlign:'center',marginVertical:30},pager:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12}});
