import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'id_number', type: 'string', isIndexed: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'local_updated_at', type: 'number' },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'negocios',
      columns: [
        { name: 'numero', type: 'number', isIndexed: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'deal_date', type: 'string', isOptional: true },
        { name: 'total_credit', type: 'number' },
        { name: 'remaining_balance', type: 'number' },
        { name: 'customer_id', type: 'string', isIndexed: true },
        { name: 'codeudor_customer_id', type: 'string', isOptional: true },
        { name: 'direccion', type: 'string', isOptional: true },
        { name: 'municipio_id', type: 'string', isOptional: true },
        { name: 'municipio_name', type: 'string', isOptional: true },
        { name: 'seller_id', type: 'string', isOptional: true },
        { name: 'gestor_cobro_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'negocio_cuotas',
      columns: [
        { name: 'negocio_id', type: 'string', isIndexed: true },
        { name: 'installment_number', type: 'number' },
        { name: 'due_date', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'paid_amount', type: 'number' },
        { name: 'late_fee_amount', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'sync_status', type: 'string' },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'negocio_pagos',
      columns: [
        { name: 'negocio_id', type: 'string', isIndexed: true },
        { name: 'cuota_id', type: 'string', isOptional: true },
        { name: 'amount', type: 'number' },
        { name: 'paid_at', type: 'string' },
        { name: 'receipt_number', type: 'string', isOptional: true },
        { name: 'virtual_receipt_number', type: 'string', isOptional: true },
        { name: 'receipt_status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by_name', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'collection_routes',
      columns: [
        { name: 'gestor_id', type: 'string', isIndexed: true },
        { name: 'route_date', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'started_at', type: 'string', isOptional: true },
        { name: 'completed_at', type: 'string', isOptional: true },
        { name: 'total_expected', type: 'number' },
        { name: 'total_collected', type: 'number' },
        { name: 'sync_status', type: 'string' },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'collection_route_stops',
      columns: [
        { name: 'route_id', type: 'string', isIndexed: true },
        { name: 'negocio_id', type: 'string', isIndexed: true },
        { name: 'negocio_numero', type: 'number' },
        { name: 'position', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'customer_name', type: 'string' },
        { name: 'customer_phone', type: 'string', isOptional: true },
        { name: 'customer_address', type: 'string' },
        { name: 'municipality_name', type: 'string', isOptional: true },
        { name: 'expected_balance', type: 'number' },
        { name: 'payment_id', type: 'string', isOptional: true },
        { name: 'payment_amount', type: 'number', isOptional: true },
        { name: 'outcome_reason', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'arrived_at', type: 'string', isOptional: true },
        { name: 'completed_at', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'catalog_municipios',
      columns: [
        { name: 'nombre', type: 'string' },
        { name: 'is_active', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'user_profile_cache',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'roles_json', type: 'string' },
        { name: 'cached_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'report_snapshots',
      columns: [
        { name: 'kind', type: 'string', isIndexed: true },
        { name: 'payload_json', type: 'string' },
        { name: 'pulled_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_outbox',
      columns: [
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'payload_json', type: 'string' },
        { name: 'idempotency_key', type: 'string', isIndexed: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'attempts', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'next_retry_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'result_json', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'sync_meta',
      columns: [
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'file_uploads',
      columns: [
        { name: 'local_uri', type: 'string' },
        { name: 'mime', type: 'string' },
        { name: 'file_name', type: 'string' },
        { name: 'bucket', type: 'string' },
        { name: 'negocio_id', type: 'string', isOptional: true },
        { name: 'pago_local_id', type: 'string', isOptional: true },
        { name: 'pago_server_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'last_error', type: 'string', isOptional: true },
      ],
    }),
  ],
});
